apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: front
  replicas: 2
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: {{REGION}}.ocir.io/{{NAMESPACE}}/clouddemo-micro/front:latest
          resources:
            requests:
              cpu: "0.1"
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: docker-wallet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 4
  template:
    metadata:
      labels:
        app: api
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: api
      containers:
        - name: api
          image: {{REGION}}.ocir.io/{{NAMESPACE}}/clouddemo-micro/api:latest
          resources:
            requests:
              cpu: "0.5"
          volumeMounts:
            - mountPath: "/home/opc/.oci"
              name: oci-wallet
              readOnly: true
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: docker-wallet
      volumes:
        - name: oci-wallet
          secret:
            secretName: oci-wallet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 2
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: {{REGION}}.ocir.io/{{NAMESPACE}}/clouddemo-micro/db:latest
          resources:
            requests:
              cpu: "0.1"
          volumeMounts:
            - mountPath: "/opt/oracle/instantclient_19_5/network/admin"
              name: db-wallet
              readOnly: true
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DBPW
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: CONNSTR
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: connection
      imagePullSecrets:
        - name: docker-wallet
      volumes:
        - name: db-wallet
          secret:
            secretName: db-wallet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wc
spec:
  selector:
    matchLabels:
      app: wc
  replicas: 2
  template:
    metadata:
      labels:
        app: wc
    spec:
      containers:
        - name: wc
          image: {{REGION}}.ocir.io/{{NAMESPACE}}/clouddemo-micro/wc:latest
          resources:
            requests:
              cpu: "0.1"
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: docker-wallet
