apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
spec:
  selector:
    matchLabels:
      app: front
  replicas: 2
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: {{REGION}}.ocir.io/{{NAMESPACE}}/clouddemo-micro/front:latest
          resources:
            requests:
              cpu: "0.1"
          ports:
            - containerPort: 80
              protocol: TCP
      imagePullSecrets:
        - name: docker-wallet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 2
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: {{REGION}}.ocir.io/{{NAMESPACE}}/clouddemo-micro/api:latest
          resources:
            requests:
              cpu: "0.1"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: BUCKET
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: bucket
      imagePullSecrets:
        - name: docker-wallet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr
spec:
  selector:
    matchLabels:
      app: ocr
  replicas: 4
  template:
    metadata:
      labels:
        app: ocr
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: ocr
      containers:
        - name: ocr
          image: {{REGION}}.ocir.io/{{NAMESPACE}}/clouddemo-micro/ocr:latest
          resources:
            requests:
              cpu: "0.5"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: BUCKET
              valueFrom:
                secretKeyRef:
                  name: bucket
                  key: bucket
      imagePullSecrets:
        - name: docker-wallet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  replicas: 2
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: {{REGION}}.ocir.io/{{NAMESPACE}}/clouddemo-micro/db:latest
          resources:
            requests:
              cpu: "0.1"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DBPW
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DBID
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_ocid
            - name: CONNSTR
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: connection
      imagePullSecrets:
        - name: docker-wallet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wc
spec:
  selector:
    matchLabels:
      app: wc
  replicas: 2
  template:
    metadata:
      labels:
        app: wc
    spec:
      containers:
        - name: wc
          image: {{REGION}}.ocir.io/{{NAMESPACE}}/clouddemo-micro/wc:latest
          resources:
            requests:
              cpu: "0.1"
          ports:
            - containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: docker-wallet
